on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

env:
  BOT_API_TOKEN: ${{ secrets.BOT_API_TOKEN }}
  SUPPORT_DEVELOPMENT_CHANNEL_ID: ${{ secrets.SUPPORT_DEVELOPMENT_CHANNEL_ID }}
  SUPPORT_GUILD_ID: ${{ secrets.SUPPORT_GUILD_ID }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      #1 Checkout the repo
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Setup bun'
        uses: oven-sh/setup-bun@v1

      - name: 'Install pnpm'
        uses: pnpm/action-setup@v4
        with:
          version: 10.20.0

      - name: 'Install dependencies'
        run: pnpm install

      - name: 'Run tests'
        run: echo "Running tests..."
          pnpm test
